In [ ]:
#Q 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
#enhance Python's capabilities for numerical operations?

In [ ]:
# NumPy (Numerical Python) is a core library in Python for numerical and scientific computing. It provides efficient, high-performance tools for working with arrays, matrices, and numerical data, making it a cornerstone for scientific computing and data analysis tasks.
# Advantages of NumPy

#    1. Efficient Array Operations:
#         NumPy introduces the ndarray object, which provides fast and memory-efficient storage of homogeneous data.
#         Operations on arrays are vectorized, allowing element-wise operations to be performed efficiently without writing explicit loops.

#   2.  Mathematical Functionality:
#         It includes a wide range of mathematical functions for operations such as linear algebra, Fourier transformations, random number generation, and statistics.
#         Supports element-wise operations and aggregate functions (e.g., sum, mean, std).

#    3. High Performance:
#         NumPy is implemented in C and Fortran, making its operations significantly faster than equivalent pure Python code.
#         It optimizes memory usage by leveraging contiguous storage and efficient broadcasting.

#   4.  Ease of Integration:
#         Compatible with other libraries such as SciPy, Pandas, Matplotlib, and scikit-learn, enhancing its utility in data analysis pipelines.
#         Allows seamless integration with code written in C, C++, and Fortran.

#   5.  Support for Multidimensional Data:
#         Enables the creation and manipulation of multidimensional arrays (e.g., 2D matrices, 3D tensors), making it ideal for data structures in machine learning and scientific computation.

#   6.  Broadcasting:
#         Provides a powerful mechanism to perform operations on arrays of different shapes and sizes without explicit replication.

#   7.  Reproducibility and Debugging:
#         With consistent random number generators and stable algorithms, NumPy ensures reproducibility in scientific experiments.

# Enhancing Python's Capabilities for Numerical Operations

#     1.Improved Speed:
#         Python's default lists are not optimized for numerical computations. NumPy offers significant speed-ups by using optimized C-based computations under the hood.

#    2. Reduced Code Complexity:
#         With vectorized operations, NumPy eliminates the need for manual loops, making the code shorter, cleaner, and easier to understand.

#     3.Advanced Indexing and Slicing:
#         NumPy provides advanced mechanisms for selecting, modifying, and querying subsets of data, which are more powerful than Python's native list slicing.

#    4. Standardization:
#         As a foundational library, NumPy offers a consistent API for numerical tasks, ensuring that scientific codebases can rely on a standardized set of tools.

#    5. Foundation for Other Libraries:
#         Many Python libraries for data analysis, machine learning, and visualization are built on top of NumPy, leveraging its robust computational backend.

In [ ]:
# Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
# other?


In [ ]:
# The np.mean() and np.average() functions in NumPy are both used to calculate the average of numerical data. However, they differ in functionality and use cases due to their implementation and flexibility. Here's a detailed comparison:

In [ ]:
# 1. Functionality
# np.mean()
np.average()

#     Purpose: Computes the arithmetic mean (average) of the elements in an array.
#     Weights: Does not support weighted averages. Each element is treated

In [ ]:
# Purpose: Computes the weighted average of the elements in an array.
# Weights: Supports weighted averages through the weights parameter.

In [ ]:
# Key Parameters:

#     a: Input array.
#     axis: The axis along which to compute the mean (default: flatten the array).
#     dtype: Data type of the output.
#     out: Alternate output array.
#     keepdims: Keeps the dimensions of the result consistent with the input.

In [ ]:
# Use Cases
# When to Use np.mean():

#     Use np.mean() for simple arithmetic mean calculations when all elements are equally important.

In [ ]:
# When to Use np.average():

#     Use np.average() when you need to compute a weighted average, where certain elements have more significance than others.

In [ ]:
# Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
# arrays.

In [ ]:
#Reversing a NumPy array along different axes is a common operation that can be accomplished using slicing, specialized functions, or methods like np.flip. Below is an explanation of the methods and examples for 1D and 2D arrays.

In [ ]:
# 1. Using Slicing ([::-1])

# Slicing is the simplest way to reverse an array along an axis.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr[::-1, :]
print(reversed_rows)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Using np.flip

# np.flip reverses an array along the specified axis

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
flipped_arr = np.flip(arr)
print(flipped_arr)


[5 4 3 2 1]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_rows = np.flip(arr, axis=0)
print(flipped_rows)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# 3. Using np.flipud and np.fliplr

#     np.flipud: Flips the array upside down (reverses along rows).
#     np.fliplr: Flips the array left to right (reverses along columns).

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flip upside down (rows):
flipped_ud = np.flipud(arr)
print(flipped_ud)





[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Flip left to right (columns):
flipped_lr = np.fliplr(arr)
print(flipped_lr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# Using np.roll

# While not strictly reversing, np.roll can shift the array's elements. Negative rolling can mimic some reverse operations.
# 1D Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
rolled_arr = np.roll(arr, -len(arr) // 2)
print(rolled_arr)


[4 5 1 2 3]


In [ ]:
# Q 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance


In [ ]:
# Determining the Data Type of Elements in a NumPy Array

# You can determine the data type of elements in a NumPy array using the .dtype attribute.

In [ ]:
# import numpy as np

 # Create a NumPy array
# arr = np.array([1, 2, 3])

# Check the data type
# print(arr.dtype)  # Output: int64 (or a platform-dependent integer type)
# Importance of Data Types in NumPy

#     Efficient Memory Management:
#         NumPy arrays store data in a contiguous memory block, and the data type defines how much memory each element occupies.
#         For example, int32 takes 4 bytes per element, while int64 takes 8 bytes.
#         Using an appropriate data type can significantly reduce memory consumption when working with large datasets.

In [ ]:
# # Memory usage comparison
# arr_32 = np.array([1, 2, 3], dtype=np.int32)
# arr_64 = np.array([1, 2, 3], dtype=np.int64)

# print(arr_32.nbytes)
# print(arr_64.nbytes)


In [ ]:
# Performance Optimization:

#     Smaller data types can lead to faster computations as less memory needs to be accessed and manipulated.
#     For example, using float32 instead of float64 for neural networks is common in machine learning because it balances precision and performance.

# Precision and Accuracy:

#     Data types like float32 and float64 affect the precision of calculations.
#     For high-precision scientific computations, you may need float64 or float128.

In [ ]:
a = np.array([0.1, 0.2], dtype=np.float32)
b = np.array([0.1, 0.2], dtype=np.float64)

print(np.sum(a))
print(np.sum(b))

0.3
0.30000000000000004


In [ ]:
# Type Compatibility:

#     NumPy operations automatically adjust to the highest precision data type involved, ensuring consistency during calculations.
#     Explicitly setting data types avoids unintended type casting.

In [ ]:
# Control Over Data:

#     Explicit data typing helps ensure that your program handles data as expected, especially when interacting with external systems or performing serialization.

In [ ]:
# definition of andarray in NumPy

# The ndarray (N-dimensional array) is the core data structure in NumPy. It is a multidimensional, homogeneous container for numerical data, designed for efficient computation and manipulation. Unlike Python lists, ndarrays are optimized for numerical operations and large datasets.
# Key Features of ndarray

#     Homogeneous Data:
#         All elements in an ndarray must be of the same data type, ensuring consistency and efficiency in operations.
#         The data type is defined by the dtype attribute.

#     N-dimensional:
#         Supports multidimensional arrays, allowing storage of 1D, 2D, 3D, or higher-dimensional data.
#         The shape of the array is accessible via the .shape attribute.

#     Efficient Memory Usage:
#         Data is stored contiguously in memory, reducing overhead compared to Python lists.
#         Allows operations to be performed in place without creating additional copies.

#     Optimized for Mathematical Operations:
#         Supports element-wise operations, broadcasting, and aggregation functions (e.g., sum, mean, etc.) efficiently.

#     Support for Vectorized Operations:
#         Eliminates the need for explicit loops, enabling concise and faster code execution.
#         Operations on entire arrays are performed in parallel using optimized C libraries.

#     Flexible Indexing and Slicing:
#         Provides powerful indexing and slicing capabilities for selecting or modifying data.
#         Allows Boolean masking and fancy indexing for complex selections.

#     Interoperability:
#         Easily integrates with other libraries like Pandas, Matplotlib, and scikit-learn.
#         Compatible with external C, C++, and Fortran libraries for advanced computations.

In [ ]:
# Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations

# NumPy arrays (ndarray) are significantly faster and more memory-efficient than Python lists for numerical operations, particularly at scale. This is due to their optimized implementation and design, which takes advantage of low-level optimizations and specialized libraries.
# 1. Vectorized Operations

#     Explanation: NumPy allows vectorized operations, enabling operations to be applied to entire arrays without explicit loops. This eliminates the overhead of Python's interpreted loops and leverages underlying C libraries for efficiency.
#     Example:

In [ ]:
import numpy as np

# NumPy array
arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)



[2 4 6 8]


In [ ]:
lst = [1, 2, 3, 4]
result = [x * 2 for x in lst]
print(result)

[2, 4, 6, 8]


In [ ]:
# Memory Efficiency

#     Explanation: NumPy arrays store elements in contiguous memory blocks with a fixed data type. Python lists are heterogeneous, storing pointers to objects, which increases memory overhead.
#     Example:

In [ ]:
# Faster Computations

#     Explanation: NumPy operations are implemented in C and optimized for speed, whereas Python lists rely on slower interpreted loops.

In [ ]:
# Built-in Mathematical Functions

#     Explanation: NumPy provides a wide range of mathematical functions (e.g., np.sum, np.mean, np.linalg.norm) implemented in optimized C code.

In [ ]:
# Broadcasting

#     Explanation: NumPy supports broadcasting, which allows operations on arrays of different shapes without creating intermediate arrays, reducing both memory usage and computation time.

In [ ]:
# Multidimensional Data Support

#     Explanation: NumPy arrays are designed to handle multidimensional data efficiently, while Python lists require nested structures and loops.

In [ ]:
#  Interoperability with Other Libraries

#     NumPy arrays integrate seamlessly with libraries like Pandas, scikit-learn, TensorFlow, and Matplotlib, which further enhances performance in data analysis and machine learning workflows.

In [ ]:
#Q 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
#output.

In [ ]:
# Comparison of vstack() and hstack() in NumPy

# The vstack() and hstack() functions in NumPy are used for stacking arrays along different axes:
# Feature	np.vstack()	np.hstack()
# Full Name	Vertical stack	Horizontal stack
# Operation	Stacks arrays along the vertical (row) axis.	Stacks arrays along the horizontal (column) axis.
# Resulting Shape	Increases the number of rows (axis=0).	Increases the number of columns (axis=1).
# Input Requirements	Arrays must have the same number of columns.	Arrays must have the same number of rows.

In [ ]:
# Using np.vstack()

In [ ]:
#Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions

In [ ]:
# fliplr() (Flip Left to Right)
# Purpose: Reverses the order of elements along the second axis (columns) of a 2D or higher-dimensional array.
# Effect: Reflects the array horizontally (left-to-right).
# Dimensionality: Requires the array to have at least two dimensions.
# Use Case: Useful for flipping images or matrices horizontally.


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
flipped = np.fliplr(arr)
print(flipped)



[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# flipped = np.flipud(arr)
print(flipped)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# Effects on Array Dimensions
# 1D Array:

# fliplr() raises an error because it requires at least 2 dimensions.
# flipud() reverses the order of elements.

In [ ]:
arr = np.array([1, 2, 3])
print(np.flipud(arr))
# np.fliplr(arr) -> Raises ValueError


[3 2 1]


In [ ]:
# 2D Array:

# fliplr() reverses the columns (horizontal flip).
# flipud() reverses the rows (vertical flip).
# 3D Array:

# fliplr() flips the elements along the last axis (like flipping columns in each 2D slice).
# flipud() flips along the first axis (like flipping rows across the depth of the array).


In [ ]:
#Q.9Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
# The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is similar to the split() method but more flexible, as it can handle uneven splits. Here's a detailed explanation:

# Functionality of array_split()
# Purpose: Divides an array into sub-arrays along a specified axis.

In [ ]:
# numpy.array_split(array, indices_or_sections, axis=0)
# array: The input array to be split.
# indices_or_sections: Specifies how to split the array.
# If an integer n is provided, the array is split into n sub-arrays. If the array cannot be evenly divided, the last sub-arrays may have fewer elements.
# If a sequence of indices is provided, it splits the array at those specific indices.
# axis: The axis along which to split the array (default is 0).

In [ ]:
# Handling Uneven Splits
# When the array cannot be evenly divided into the specified number of sections:

# array_split() automatically adjusts the sizes of the sub-arrays.
# It ensures all elements are included, with sub-arrays having nearly equal sizes.
# If the array size isn't a multiple of the number of splits, some sub-arrays will be slightly larger than others (by one element).


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, [2, 4])
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, [2, 4])
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# ey Differences from split()
# split() requires the array to be evenly divisible by the number of splits, and it raises a ValueError if not.
# array_split() gracefully handles uneven splits, making it more robust in real-world scenarios.


In [ ]:
#Q 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?

In [ ]:
# 1. Vectorization
# Concept:
# Vectorization refers to performing operations on entire arrays (or vectors) at once, rather than iterating over individual elements.
# Operations are applied element-wise across the array, taking advantage of optimized, low-level implementations.
# Benefits:
# Speed: Operations are performed in compiled C code, which is much faster than Python loops.
# Conciseness: Eliminates the need for explicit loops, making the code shorter and easier to read.
# Parallelism: Internally, vectorized operations may utilize parallel processing for further speedu

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
squared = [x**2 for x in arr]
print(squared)



[1, 4, 9, 16]


In [ ]:
squared = arr**2
print(squared)



[ 1  4  9 16]


In [ ]:
# Broadcasting
# Concept:
# Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array along dimensions where sizes differ.
# Instead of replicating data explicitly (which is memory-inefficient), NumPy optimizes the operation by virtually expanding the smaller array.
# Rules for Broadcasting:
# If the dimensions of the arrays differ, prepend ones to the smaller array's shape until they match in length.
# Arrays are compatible if, for each dimension:
# Their sizes are the same, or
# One of them is 1.
# If compatible, NumPy broadcasts the smaller array along the mismatched dimensions to match the shape of the larger array.
# Example:
# Broadcasting a scalar:

arr = np.array([1, 2, 3, 4])
result = arr + 5
print(result)



[6 7 8 9]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)



[[11 22 33]
 [14 25 36]]


In [ ]:
# Performance Comparison
# Example: Adding two arrays element-wise.

In [ ]:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = np.zeros_like(arr1)
for i in range(len(arr1)):
    result[i] = arr1[i] + arr2[i]

result = arr1 + arr2


In [ ]:

#PRACTICAL QUESTION

In [ ]:
# Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
# To create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns (also known as transposing the matrix), you can use the following Python code:

In [2]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

transposed_array = array.T

print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 2 20 65]
 [71  8 28]
 [81 35 39]]

Transposed array:
[[ 2 71 81]
 [20  8 35]
 [65 28 39]]


In [3]:
#Q .2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.



In [38]:
# To generate a 1D NumPy array with 10 elements and reshape it into a 2x5 array, and then into a 5x2 array, you can use the following Python code:

import numpy as np

array = np.arange(10)

print("Original 1D array:")
print(array)

array_2x5 = array.reshape(2, 5)

print("\nReshaped into 2x5 array:")
print(array_2x5)

array_5x2 = array.reshape(5, 2)

print("\nReshaped into 5x2 array:")
print(array_5x2)



Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
#Q.3Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.



In [10]:
#To create a 4x4 NumPy array with random float values and then add a border of zeros around it to make it a 6x6 array, you can use the following Python code:

In [39]:
import numpy as np
array = np.random.random((4, 4))
print("Original 4x4 array:")
print(array)

array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 array with border of zeros:")
print(array_with_border)


Original 4x4 array:
[[0.35892508 0.12445967 0.58758653 0.82379085]
 [0.74271619 0.16850539 0.53378523 0.78765915]
 [0.3089255  0.78162517 0.70275337 0.25919209]
 [0.29848763 0.77014726 0.21047747 0.1990716 ]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.35892508 0.12445967 0.58758653 0.82379085 0.        ]
 [0.         0.74271619 0.16850539 0.53378523 0.78765915 0.        ]
 [0.         0.3089255  0.78162517 0.70275337 0.25919209 0.        ]
 [0.         0.29848763 0.77014726 0.21047747 0.1990716  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [12]:
#Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.



In [13]:
#To create a NumPy array of integers from 10 to 60 with a step of 5, you can use np.arange(). Here's the Python code:

In [14]:
import numpy as np

array = np.arange(10, 61, 5)

print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [40]:
#Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

#To create a NumPy array of integers from 10 to 60 with a step of 5, you can use np.arange(). Here's the Python code:

import numpy as np

array = np.arange(10, 61, 5)

print(array)



[10 15 20 25 30 35 40 45 50 55 60]


In [21]:
#To generate a NumPy array of words and insert a space between each character of every word, you can use the np.char.add function to concatenate spaces between the characters. Here's the Python code to achieve this:

In [19]:
import numpy as np

words = np.array(['python', 'numpy', 'pandas'])
spaced_words = np.char.add(' ', np.char.join(' ', words))

print("Original words array:")
print(words)

print("\nWords with spaces between characters:")
print(spaced_words)


Original words array:
['python' 'numpy' 'pandas']

Words with spaces between characters:
[' p y t h o n' ' n u m p y' ' p a n d a s']


In [25]:
#Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [26]:
#You can achieve this by creating a NumPy array of words, then inserting a space between each character in every word. Here's how you can do it using Python with the NumPy library:

In [42]:
import numpy as np

words = np.array(['hello', 'world', 'numpy', 'array'])
def space_characters(word):
    return ' '.join(word)
spaced_words = np.vectorize(space_characters)(words)
print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [43]:
#Q 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

#You can create two 2D NumPy arrays and perform various element-wise operations like addition, subtraction, multiplication, and division using NumPy. Here's an example:

import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
addition = array1 + array2
print("Element-wise Addition:\n", addition)
subtraction = array1 - array2
print("\nElement-wise Subtraction:\n", subtraction)
multiplication = array1 * array2
print("\nElement-wise Multiplication:\n", multiplication)
division = array1 / array2
print("\nElement-wise Division:\n", division)


Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [29]:
#Q 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.



In [44]:
#You can create a 5x5 identity matrix using NumPy's np.eye() function and then extract its diagonal elements using the np.diagonal() method. Here’s how you can do it:

import numpy as np
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [31]:
#Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.

#To generate a NumPy array of 100 random integers between 0 and 1000 and then find and display all prime numbers from that array, you can follow the steps below. First, we will generate the array and then define a function to check for prime numbers.

In [56]:
import numpy as np
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers:\n", random_integers)
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n*0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime Numbers in the Array:\n", prime_numbers)

Random Integers:
 [429  66 257 890 843 349 625 193 906 487 358 249 663  82 359 480 975 467
 846 970 655 579 154 309 756 282 439  96 645 176 838 911 722 998 640 675
 286 127 381 525 456 239 691   7 253  82  27  56 906 932 331 734 494 127
 795 484 250 316  82 521 735 194 221 737 881 919 742 792 614 221 597 331
 908 891 471 348 176 269 725 463  42 804 307 242 301 661 955 202 489 625
  44 471 465 405 846 598   0 496 370 351]

Prime Numbers in the Array:
 [257, 349, 193, 487, 359, 467, 439, 911, 127, 239, 691, 7, 331, 127, 521, 881, 919, 331, 269, 463, 307, 661]


In [49]:
#Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.


In [55]:
import numpy as np
daily_temperatures = np.random.uniform(0, 40, size=30)
print("Daily Temperatures for the Month:\n", daily_temperatures)
weekly_temperatures = daily_temperatures.reshape(5,6)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Averages:\n", weekly_averages)

Daily Temperatures for the Month:
 [11.59186181  0.32012445 36.43061546 17.3935751  22.93166459  1.14095086
 28.50861547  4.94334272 26.1883224  35.30064081 25.0876923   2.93957732
  9.15011227 31.38246641 10.95968976 17.3441265  39.28656132 12.28900703
 12.66883372 28.29304052 35.31416452 35.82291588 34.95354717 36.92818061
 35.53991271 27.20256276 19.82644236 33.31306584 10.64393756 28.94176859]

Weekly Averages:
 [14.96813205 20.49469851 20.06866055 30.66344707 25.91128164]
